"""
features.py
============
Feature-engineering utilities consumed by the Prophet pipeline.
Adds US holidays, weather regressors, price, promo flags, and
cyclical time features.
"""

from __future__ import annotations

from typing import Optional

import numpy as np
import pandas as pd
from prophet import Prophet

# ---------------------------------------------------------------------------
# US holidays that meaningfully affect strawberry demand
# (Actual rows are generated by _expand_holidays() below.)
# ---------------------------------------------------------------------------
US_HOLIDAY_NAMES: list[str] = [
    "SuperBowl", "ValentinesDay", "Easter", "MothersDay",
    "MemorialDay", "July4th", "LaborDay",
    "Thanksgiving", "Christmas", "NewYear",
]


def _expand_holidays(years: list[int]) -> pd.DataFrame:
    """Return a DataFrame of holiday rows covering *years* with pre/post windows."""
    records: list[dict] = []
    for y in years:
        records += [
            {"holiday": "NewYear",        "ds": f"{y}-01-01", "lower_window": -3, "upper_window": 1},
            {"holiday": "SuperBowl",      "ds": f"{y}-02-12", "lower_window": -7, "upper_window": 0},
            {"holiday": "ValentinesDay",  "ds": f"{y}-02-14", "lower_window": -5, "upper_window": 0},
            {"holiday": "Easter",         "ds": f"{y}-04-10", "lower_window": -7, "upper_window": 1},
            {"holiday": "MothersDay",     "ds": f"{y}-05-12", "lower_window": -7, "upper_window": 0},
            {"holiday": "MemorialDay",    "ds": f"{y}-05-27", "lower_window": -3, "upper_window": 1},
            {"holiday": "July4th",        "ds": f"{y}-07-04", "lower_window": -3, "upper_window": 1},
            {"holiday": "LaborDay",       "ds": f"{y}-09-02", "lower_window": -3, "upper_window": 1},
            {"holiday": "Thanksgiving",   "ds": f"{y}-11-28", "lower_window": -5, "upper_window": 1},
            {"holiday": "Christmas",      "ds": f"{y}-12-25", "lower_window": -7, "upper_window": 1},
        ]
    df = pd.DataFrame(records)
    df["ds"] = pd.to_datetime(df["ds"])
    return df


def add_regressor_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Ensure all regressor columns exist and are float64."""
    required = [
        "avg_temp_f", "precip_inches", "is_promo",
        "avg_price_usd", "holiday_window",
        "month_sin", "month_cos",
    ]
    for col in required:
        if col not in df.columns:
            raise ValueError(f"Missing regressor column: {col}")
        df[col] = df[col].astype(float)
    return df


def build_future_features(
    df_hist: pd.DataFrame,
    periods: int = 3,
    freq: str = "W-MON",
) -> pd.DataFrame:
    """
    Build a future dataframe for *periods* weeks using simple heuristics
    for the regressor columns (rolling averages of the historical tail).
    In production this would pull from a weather API + internal promo calendar.
    """
    last_date = df_hist["ds"].max()
    future_dates = pd.date_range(
        start=last_date + pd.Timedelta(days=7),
        periods=periods,
        freq=freq,
    )
    future = pd.DataFrame({"ds": future_dates})

    # Carry forward rolling-4-week averages for continuous features
    tail = df_hist.tail(4)
    future["avg_temp_f"] = tail["avg_temp_f"].mean()
    future["precip_inches"] = tail["precip_inches"].mean()
    future["avg_price_usd"] = tail["avg_price_usd"].mean()

    # Default: no promo in future (override as needed)
    future["is_promo"] = 0.0

    # Holiday window heuristic
    future["holiday_window"] = future["ds"].apply(
        lambda d: 1.0 if d.month in (2, 5, 7, 9, 11, 12) else 0.0
    )

    # Cyclical month
    future["month_sin"] = np.sin(2 * np.pi * future["ds"].dt.month / 12)
    future["month_cos"] = np.cos(2 * np.pi * future["ds"].dt.month / 12)

    return future


def configure_prophet(
    years: Optional[list[int]] = None,
    yearly_seasonality: int = 10,
    weekly_seasonality: bool = False,
    daily_seasonality: bool = False,
) -> Prophet:
    """
    Return a Prophet instance pre-loaded with holidays and regressors.
    """
    if years is None:
        years = list(range(2019, 2027))

    holidays_df = _expand_holidays(years)

    model = Prophet(
        growth="linear",
        holidays=holidays_df,
        yearly_seasonality=yearly_seasonality,
        weekly_seasonality=weekly_seasonality,
        daily_seasonality=daily_seasonality,
        changepoint_prior_scale=0.05,
        holidays_prior_scale=10.0,
        seasonality_prior_scale=10.0,
        interval_width=0.95,
    )

    # Register extra regressors
    model.add_regressor("avg_temp_f", prior_scale=10, mode="additive")
    model.add_regressor("precip_inches", prior_scale=10, mode="additive")
    model.add_regressor("is_promo", prior_scale=10, mode="additive")
    model.add_regressor("avg_price_usd", prior_scale=10, mode="additive")
    model.add_regressor("holiday_window", prior_scale=10, mode="additive")
    model.add_regressor("month_sin", prior_scale=5, mode="additive")
    model.add_regressor("month_cos", prior_scale=5, mode="additive")

    return model
